spring:
  jpa:
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

#  h2:
#    console:
#      enabled: true

#  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:mem:testdb

  profiles:
    include: oauth

  session:
    store-type: jdbc
